### ISSUE TITLE
Arguments mixing flags and code?

### ISSUE THREAD

**Issue by dsblank** [blink1073/metakernel#56]
The main problem probably isn't a bug, but just a limitation of the system, and maybe even necessary to do the right thing. (But there is a crash at the bottom that should be fixed).

Rules:
* If a magic takes a single thing, then the arg parser will correctly pack it altogether 
* If a magic takes flags (or required params), it will break into parts, parsing the pieces
* A magic can't automatically do both of the above

So, if you have a magic that is supposed to pass everything given to it:
```
%somemagic this is all one thing -ok --flag
```
and line_somemagic is defined to only have a single parameter, then all is fine (and the entire line is passed in as a string argument). But if somemagic can also take a flag, then you have to use it like:

```
%somemagic "this is all one thing -ok" --flag
```

Otherwise, you get the crash as seen below:

```
$ ipython console --kernel metakernel_python 
IPython Console 3.0.0-dev

In [1]: %kernel metakernel.process_metakernel BashKernel
Out[1]: <metakernel.process_metakernel.BashKernel object at 0x7f10f813fd90>

In [2]: %kx ls
Out[2]: u'chatbot.py  Makefile  processing.py  prolog.py  scheme.py\r\n'

In [3]: %kx ls -l
Usage: metakernel_python.py [options]

metakernel_python.py: error: no such option: -l
ERROR:tornado.general:Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/home/dblank/ipython3/local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 407, in _run_callback
    callback(*args, **kwargs)
  File "/home/dblank/ipython3/local/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/dblank/ipython3/local/lib/python2.7/site-packages/IPython/kernel/zmq/kernelbase.py", line 249, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/dblank/ipython3/local/lib/python2.7/site-packages/IPython/kernel/zmq/kernelbase.py", line 210, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/dblank/ipython3/local/lib/python2.7/site-packages/IPython/kernel/zmq/kernelbase.py", line 357, in execute_request
    user_expressions, allow_stdin)
  File "/home/dblank/ipython3/local/lib/python2.7/site-packages/metakernel-0.3-py2.7.egg/metakernel/_metakernel.py", line 231, in do_execute
    magic = self.get_magic(code)
  File "/home/dblank/ipython3/local/lib/python2.7/site-packages/metakernel-0.3-py2.7.egg/metakernel/_metakernel.py", line 508, in get_magic
    return magic.get_magic(info)
  File "/home/dblank/ipython3/local/lib/python2.7/site-packages/metakernel-0.3-py2.7.egg/metakernel/magics/magic_magic.py", line 77, in get_magic
    minfo['code'], minfo['args'])
  File "/home/dblank/ipython3/local/lib/python2.7/site-packages/metakernel-0.3-py2.7.egg/metakernel/magic.py", line 28, in call_magic
    args, kwargs = _parse_args(func, args)
  File "/home/dblank/ipython3/local/lib/python2.7/site-packages/metakernel-0.3-py2.7.egg/metakernel/magic.py", line 128, in _parse_args
    value, args = parser.parse_args(args)
  File "/usr/lib/python2.7/optparse.py", line 1402, in parse_args
    self.error(str(err))
  File "/usr/lib/python2.7/optparse.py", line 1584, in error
    self.exit(2, "%s: error: %s\n" % (self.get_prog_name(), msg))
  File "/usr/lib/python2.7/optparse.py", line 1574, in exit
    sys.exit(status)
SystemExit: 2
```
These works:
```
In [4]: %kx "ls -l"
In [5]: %kx "ls -l" -k default
```
because %kx also takes -k. Can we catch this, and pass all in as a string? Probably too much magic to try to parse the "-k default" out---maybe just treat as long string, even though that is not correct?

**Comment by blink1073** [comment]
Sorry Doug, I missed this one, looking now.

**Comment by blink1073** [comment]
How's this behaviour:

```python
In [2]: %kx ls -l
Magic Parse error: "no such option: -l"
Out[2]: <metakernel.process_metakernel.BashKernel object at 0x7f9a2c0b07f0>
Usage: %kx CODE [-k NAME] - send the code to the kernel.

This line magic will send the CODE to the kernel
for execution.

Returns the result of the execution as output.

Example:

    %kernel ls -al

Use `%kernel MODULE CLASS [-k NAME]` to create a kernel.

Options:
-------
-k --kernel_name kernel name given to use for execution [default: None]
```

**Comment by blink1073** [comment]
Perhaps the example should include the quotation marks?

**Comment by blink1073** [comment]
The other option I see is to treat the whole thing as one string argument if parsing fails.  Anything beyond that is to "cute" I think.

**Comment by blink1073** [comment]
I just remembered, the standard way to do this is to add a '--' separator.  So, we can check for a standalone `--` and everything to the left is combined into one argument.  (e.g. `%kx ls -l -- -k temp` -> `%kx "ls -l" -k temp`.

**Comment by dsblank** [comment]
Good idea... I like that!

**Comment by blink1073** [comment]
Otherwise I think we should use "graceful error" version from the code snippet above and add `--` handling, agreed?

**Comment by blink1073** [comment]
But it sure would be nice to just use `%kx ls -l`. How about this: move down the list looking for options.  If they are in the option set, partition the list there and pass the rest to the parser, grouping everything to the left.

**Comment by blink1073** [comment]
But then fall back on the "graceful error".

**Comment by dsblank** [comment]
Both of those (move down list, and fallback to error) sound fine.

**Comment by blink1073** [comment]
It needs some tests added, but it works.

**Comment by blink1073** [comment]
All set!

**Comment by blink1073** [comment]
Close this one?

**Comment by dsblank** [comment]
Looks good to me! Thanks!
